### ISSUE TITLE
Unable to deploy Grav to Cloud Run

### ISSUE THREAD

**Issue by szxyks** [getgrav/docker-grav#61]
I've tried Grav on my personal computer and it worked like a charm. I've been trying to deploy it to Google Cloud Run using the below command:

`docker build -t grav .; docker tag grav gcr.io/project-name/grav; docker push gcr.io/project-name/grav; gcloud run deploy grav --image gcr.io/project-name/grav --platform managed --region us-east1 --allow-unauthenticated --port 8000`

The deployment keeps failing with the following error:

`ERROR: (gcloud.run.deploy) Revision 'grav-00005-5g7' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8000 environment variable`

I even added the following entry in the Dockerfile:
`EXPOSE 8000`

It still fails with the same error. May I please have some help deploying Grav to Cloud Run? I followed the simeple steps here on this [doc](https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-php-service) and it works without issues

**Comment by szxyks** [comment]
After modifying the Dockerfile below, I was able to deploy it to Cloud Run:

```
FROM php:7.4-apache
LABEL maintainer="Andy Miller <rhuk@getgrav.org> (@rhukster)"

# Enable Apache Rewrite + Expires Module
RUN a2enmod rewrite expires && \
    sed -i 's/ServerTokens OS/ServerTokens ProductOnly/g' /etc/apache2/conf-available/security.conf

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    unzip \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libyaml-dev \
    libzip4 \
    libzip-dev \
    zlib1g-dev \
    libicu-dev \
    g++ \
    git \
    cron \
    vim \
    && docker-php-ext-install opcache \
    && docker-php-ext-configure intl \
    && docker-php-ext-install intl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install zip \
    && pecl install apcu \
    && pecl install yaml-2.0.4 \
    && docker-php-ext-enable apcu yaml \
    && rm -rf /var/lib/apt/lists/*

# Set recommended PHP.ini settings
RUN { \
    echo 'opcache.memory_consumption=128'; \
    echo 'opcache.interned_strings_buffer=8'; \
    echo 'opcache.max_accelerated_files=4000'; \
    echo 'opcache.revalidate_freq=2'; \
    echo 'opcache.fast_shutdown=1'; \
    echo 'opcache.enable_cli=1'; \
    echo 'upload_max_filesize=128M'; \
    echo 'post_max_size=128M'; \
    echo 'expose_php=off'; \
    } > /usr/local/etc/php/conf.d/php-recommended.ini

# Set user to www-data
RUN chown www-data:www-data /var/www

# Define Grav specific version of Grav or use latest stable
ARG GRAV_VERSION=latest

# Install grav
WORKDIR /var/www
RUN curl -o grav-admin.zip -SL https://getgrav.org/download/core/grav-admin/${GRAV_VERSION} && \
    unzip grav-admin.zip && \
    mv -T /var/www/grav-admin /var/www/html && \
    rm grav-admin.zip

# Create cron job for Grav maintenance scripts
RUN (crontab -l; echo "* * * * * cd /var/www/html;/usr/local/bin/php bin/grav scheduler 1>> /dev/null 2>&1") | crontab -

# provide container inside image for data persistence
VOLUME ["/var/www/html"]

# Ensure the container listens on the port specified by the PORT environment variable
ENV PORT 80
EXPOSE $PORT

# Start cron and Apache
CMD ["sh", "-c", "cron && apache2-foreground"]
```

```
Deploying container to Cloud Run service [grav] in project [project-name] region [us-east1]
OK Deploying... Done.                                                                                                                                                                                                                                                        
  OK Creating Revision...                                                                                                                                                                                                                                                    
  OK Routing traffic...                                                                                                                                                                                                                                                      
  OK Setting IAM Policy...                                                                                                                                                                                                                                                   
Done.                                                                                                                                                                                                                                                                        
Service [grav] revision [grav-00010-mmc] has been deployed and is serving 100 percent of traffic.
Service URL: https://grav-44xwb36ata-ue.a.run.app
```

Now when I try to access the URL, I'm getting above:

`Fatal error: Uncaught RuntimeException: Failed to save file /var/www/html/user/config/security.yaml in /var/www/html/vendor/rockettheme/toolbox/File/src/AbstractFile.php:374 Stack trace: #0 /var/www/html/system/src/Grav/Common/File/CompiledFile.php(133): RocketTheme\Toolbox\File\AbstractFile->save(NULL) #1 /var/www/html/system/src/Grav/Common/Config/Setup.php(416): Grav\Common\File\CompiledYamlFile->save() #2 /var/www/html/system/src/Grav/Common/Config/Setup.php(294): Grav\Common\Config\Setup->check(Object(RocketTheme\Toolbox\ResourceLocator\UniformResourceLocator)) #3 /var/www/html/system/src/Grav/Common/Service/ConfigServiceProvider.php(40): Grav\Common\Config\Setup->init() #4 /var/www/html/vendor/pimple/pimple/src/Pimple/Container.php(122): Grav\Common\Service\ConfigServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) #5 /var/www/html/system/src/Grav/Common/Grav.php(217): Pimple\Container->offsetGet('setup') #6 /var/www/html/system/src/Grav/Common/Grav.php(258): Grav\Common\Grav->setup() #7 /var/www in /var/www/html/system/src/Grav/Common/Config/Setup.php on line 420`

Please help...

**Comment by szxyks** [comment]
I was able to fix the problem using :
`RUN chown -R www-data:www-data /var/www`
